version: '3.7'
services:
  iris:
    image: datasetexplorer
    build:
      context: .
      dockerfile : Dockerfile-python
      args:
        - IRIS_PASSWORD=${IRIS_PASSWORD:-SYS}
    volumes:
      - .:/tmp/iris
    command: -a "sh /opt/irisapp/flask_server_start.sh"
    ports:
    - 52775:52773
    - 51776:1972
    - 4040:8080
    - 4041:8081
  react:
    build:
      context: app
    ports:
      - 3000:80
